services:

  emulatorjs: # 服务名称
    image: lscr.io/linuxserver/emulatorjs:latest # 镜像名称（可更改冒号后版本）
    container_name: emulatorjs # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 10011:3000
      - 10010:80
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /volume1/@home/Testroot/Docker/emulatorjs/config:/config
      - /volume1/@home/Testroot/Docker/emulatorjs/data:/data
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接
  
  teamspeak: # 服务名称
    image: teamspeak:latest # 镜像名称（可更改冒号后版本）
    container_name: teamspeak # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 10020:9987/udp
      - 10021:30033
      - 10022:41144
      - 10023:10011
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /volume1/@home/Testroot/Docker/teamspeak:/var/ts3server
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: db
      TS3SERVER_DB_USER: root
      TS3SERVER_DB_PASSWORD: password
      TS3SERVER_DB_NAME: teamspeak
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接
