services:

  # 未适配群晖系统，请勿安装此 Compose 
  #nastools: # 服务名称
  #  image: nastools/nas-tools:latest # 镜像名称（可更改冒号后版本）
  #  container_name: nastools # 容器名称（可更改）
  #  ports: # 容器端口（可更改冒号前端口）
  #    - 3000:3000 
  #  volumes: # 冒号前替换成自身路径即可（可更改）
  #    - /volume1/My/Docker/nastools:/config
  #    - /volume1/My/Video:/downloads
  #  environment: # 环境变量
  #    - PUID=0
  #    - PGID=0
  #    - TZ=Asia/Shanghai
  #    - UMASK=022
  #  restart: always # 总是启动容器
  #  network_mode: bridge # 网络桥接

  moviepilot: # 服务名称
    image: jxxghp/moviepilot-v2:latest # 镜像名称（可更改冒号后版本）
    container_name: moviepilot # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 3005:3000
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /volume1/My/Video:/downloads
      - /volume1/My/Docker/moviepilot:/config
    environment: # 环境变量
      - NGINX_PORT=3000
      - PORT=3001
      - PUID=0
      - PGID=0
      - UMASK=000
      - TZ=Asia/Shanghai
      - SUPERUSER=admin
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接

  jellyfin: # 服务名称
    image: nyanmisaka/jellyfin:latest # 镜像名称（可更改冒号后版本）
    container_name: jellyfin # 容器名称（可更改）
    privileged: true # 配置最高权限
    devices:
     - /dev/dri:/dev/dri
    ports: # 容器端口（可更改冒号前端口）
      - 3010:8096
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /volume1/My/Docker/jellyfin/config:/config
      - /volume1/My/Docker/jellyfin/cache:/cache
      - /volume1/My/Video:/video
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接

  emby: # 服务名称
    image: amilys/embyserver:latest # 镜像名称（可更改冒号后版本）
    container_name: embyserver # 容器名称（可更改）
    privileged: true # 配置最高权限
    ports: # 容器端口（可更改冒号前端口）
      - 3015:8096
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /volume1/My/Docker/emby/config:/config
      - /volume1/My/Video:/data
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接

  qbittorrent: # 服务名称
    image: linuxserver/qbittorrent:4.6.6 # 镜像名称（可更改冒号后版本）
    container_name: qbittorrent # 容器名称（可更改）
    privileged: true # 配置最高权限
    ports: # 容器端口（可更改冒号前端口）
      - 3020:3020
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /volume1/My/Docker/qbittorrent:/config
      - /volume1/My/Video:/downloads
    environment: # 环境变量
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - WEBUI_PORT=3020
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接

  transmission: # 服务名称
    image: linuxserver/transmission:4.0.5 # 镜像名称（可更改冒号后版本）
    container_name: transmission # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 3025:9091
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /volume1/My/Docker/transmission:/config
      - /volume1/My/Video:/downloads
    environment: # 环境变量
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - TRANSMISSION_WEB_HOME=/config/webui/Transmission Theme
      - USER=root
      - PASS=root
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接

  iyuuplus: # 服务名称
    image: iyuucn/iyuuplus:latest # 镜像名称（可更改冒号后版本）
    container_name: iyuuplus # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 3030:8780
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /volume1/My/Docker/iyuuplus/iyuu:/iyuu
      - /volume1/My/Docker/iyuuplus/data:/data
      - /volume1/My/Docker/qbittorrent/qBittorrent/BT_backup:/qb
      - /volume1/My/Docker/transmission/torrents:/tr
    environment: # 环境变量
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接

  xunlei: # 服务名称
    image: cnk3x/xunlei:latest # 镜像名称（可更改冒号后版本）
    container_name: xunlei # 容器名称（可更改）
    privileged: true # 配置最高权限
    ports: # 容器端口（可更改冒号前端口）
      - 3035:2345
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /volume1/My/Docker/xunlei:/xunlei/data
      - /volume1/My/Downloads:/xunlei/downloads
    environment: # 环境变量
      - XL_GID=0
      - XL_UID=0
      - TZ=Asia/Shanghai
      - XL_DASHBOARD_USERNAME=admin
      - XL_DASHBOARD_PASSWORD=admin
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接  
  
  jackett: # 服务名称
    image: linuxserver/jackett:latest # 镜像名称（可更改冒号后版本）
    container_name: jackett # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 3040:9117
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /volume1/My/Docker/jackett/config:/config
      - /volume1/My/Docker/jackett/downloads:/downloads
    environment: # 环境变量
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - AUTO_UPDATE=false
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接

  aipan: # 服务名称
    image: fooololo/aipan-netdisk-search:latest # 镜像名称（可更改冒号后版本）
    container_name: aipan # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 3045:3000
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接

  vertex:
    image: lswl/vertex:latest
    container_name: vertex
    ports: # 容器端口（可更改冒号前端口）
      - 3050:32110
    volumes:
      - /volume1/My/Docker/vertex:/vertex
    environment:
      - PORT=32110
      - TZ=Asia/Shanghai
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接

  iptv-api: # 服务名称
    image: guovern/iptv-api:latest # 镜像名称（可更改冒号后版本）
    container_name: iptv-api # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 3055:8000
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /volume1/My/Docker/iptv-api/config:/iptv-api/config
      - /volume1/My/Docker/iptv-api/output:/iptv-api/output
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接
    
  metatube: # 服务名称
    image: metatube/metatube-server:latest # 镜像名称（可更改冒号后版本）
    container_name: metatube # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 3060:8080
    environment: # 环境变量
      - PORT=8080
      - DB_MAX_IDLE_CONNS=0
      - DB_MAX_OPEN_CONNS=0
      - DB_PREPARED_STMT=0
      - DB_AUTO_MIGRATE=0
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接
