# 本服务需要更换镜像源

services:

  firefox: # 服务名称
    image: jlesage/firefox:latest # 镜像名称（可更改冒号后版本）
    container_name: firefox # 容器名称（可更改）
    privileged: true # 配置最高权限
    ports: # 容器端口（可更改冒号前端口）
      - 8010:5800
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /volume1/@home/Testroot/Docker/firefox/config:/config:rw
      - /volume1/@home/Testroot/Docker/firefox/fonts:/usr/share/fonts
      - /volume1/@home/Testroot/Downloads:/config/downloads
    environment:
      - USER_ID=0
      - GROUP_ID=0
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接

  npc: # 服务名称
    image: yisier1/npc:latest # 镜像名称（可更改冒号后版本）
    container_name: npc # 容器名称（可更改）
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /volume1/@home/Testroot/Docker/npc:/conf
    command: -server=47.243.80.27:8024 -vkey=自行填写密钥 -type=tcp # 启动命令
    restart: always # 总是启动容器
    network_mode: host # 网络本地

  frpc: # 服务名称
    image: snowdreamtech/frpc # 镜像名称（可更改冒号后版本）
    container_name: frpc # 容器名称（可更改）
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /volume1/@home/Testroot/Frpc:/etc/frp
    command: -c /etc/frp/frpc.ini # 启动命令
    restart: always # 总是启动容器
    network_mode: host # 网络本地

  v2raya: # 服务名称
    image: v2raya/v2raya:latest # 镜像名称（可更改冒号后版本）
    container_name: v2raya # 容器名称（可更改）
    privileged: true
    ports: # 容器端口（可更改冒号前端口）
      - 8020:2017
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /volume1/@home/Testroot/Docker/v2raya:/etc/v2raya
    environment: # 环境变量
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接
