version: "3"

####################################################################################
# 单独启动容器
# version: "3"
# services: # 定义服务
#   wps-office: # 服务名称
#    image: linuxserver/wps-office:chinese # 镜像名称（可更改冒号后版本）
#    container_name: wps-office # 容器名称（可更改）
#    ports: # 容器端口（可更改冒号前端口）
#     - 3030:3000
#     - 3031:3001
#    volumes: # 冒号前替换成自身路径即可（可更改）
#     - /vol1/1000/Docker/wps-office/config:/config
#     - /vol1/1000/Docker/wps-office/Desktop:/config/Desktop
#     - /vol1/1000/Docker/wps-office/Fonts:/usr/share/fonts/wps-fonts
#    environment: # 环境变量
#     - PUID=0
#     - PGID=0
#     - TZ=Asia/Shanghai
#     - CUSTOM_USER=admin
#     - PASSWORD=admin
#    restart: always # 总是启动容器
#    network_mode: bridge # 网络桥接
####################################################################################

####################################################################################
# nastools       用户名：admin 密码：password
# moviepilot     用户名：admin 密码：运行日志中
# jellyfin       用户名：自定义 密码：自定义
# qbaittorrent   用户名：admin 密码：运行日志中
# transmission   用户名：root  密码：root
# iyuuplus       用户名：自定义 密码：自定义
# xunlei         用户名：admin 密码：admin
# jackett        用户名：无    密码：无
# alist-tvbox    用户名：admin 密码：admin
# apipan         用户名：无    密码：无
# vertex         用户名：admin 密码：data目录下查看
# navidrome      用户名：自定义 密码：自定义
# music-tag      用户名：admin 密码：admin
# reader         用户名：自定义 密码：自定义
# komga          用户名：自定义 密码：自定义
# wps-office     用户名：admin 密码：admin
# verysync       用户名：自定义 密码：自定义
# pdftool        用户名：无    密码：无
# kkfileview     用户名：无    密码：无
# siyuan         用户名：无    密码：无
# alist          用户名：admin 密码：运行日志中
# frpc           用户名：无    密码：无
# v2raya         用户名：自定义 密码：自定义
# sun-panel      用户名：admin@sun.cc 密码：12345678
# emulatorjs     用户名：无    密码：无
# qinglong       用户名：自定义 密码：自定义
# homeassistant  用户名：自定义 密码：自定义
####################################################################################

####################################################################################
# Compose文件夹：用于存放懒人包配置文件的
# Docker文件夹：用于存放容器的
# Downloads：用于迅雷下载文件夹
# frpc文件夹：用于存放内网穿透的
# Music文件夹：用于存放音乐的
# Synchronous：用于同步文件夹
# Video文件夹：用于存放影视的，sh脚本生成后续文件夹
####################################################################################

####################################################################################
# 如何使用懒人包
# 1、创建好Docker存储位置
# 2、创建Compose文件夹
# 3、打开FinalShell软件
# 4、进入root权限，输入 sudo -i 并输入飞牛密码，进入root权限
# 5、cd /vol1/1000/Compose 进入Compose文件夹内
# 6、输入 docker compose up -d 等待代码跑完即可
####################################################################################

####################################################################################
# docker stop $(docker ps -aq) 停止所有容器
# docker rm $(docker ps -aq) 删除所有容器
# docker rmi $(docker images -a -q) 删除所有镜像
####################################################################################

####################################################################################
# 本懒人包端口配置
# 影视 3000 - 3095
# 音乐 4000 - 4010
# 小说 5000 - 5000
# 漫画 6010 - 6010
# 办公 7000 - 7050
# 网络 8010 - 8010
# 美化 9000 - 9000
# 娱乐 10000 - 10001
# 系统 11000 - 11010
####################################################################################

services:

#######################  影视类  ############################

  #nastools: # 服务名称
  #  image: nastools/nas-tools:latest # 镜像名称（可更改冒号后版本）
  #  container_name: nastools # 容器名称（可更改）
  #  ports: # 容器端口（可更改冒号前端口）
  #    - 3000:3000 
  #  volumes: # 冒号前替换成自身路径即可（可更改）
  #    - /vol1/1000/Docker/nastools:/config
  #    - /vol1/1000/Video:/downloads
  #  environment: # 环境变量
  #    - PUID=0
  #    - PGID=0
  #    - TZ=Asia/Shanghai
  #    - UMASK=022
  #  restart: always # 总是启动容器
  #  network_mode: bridge # 网络桥接

  moviepilot: # 服务名称
    image: jxxghp/moviepilot-v2:latest # 镜像名称（可更改冒号后版本）
    container_name: moviepilot # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 3000:3000
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /vol1/1000/Video:/downloads
      - /vol1/1000/Docker/moviepilot:/config
    environment: # 环境变量
      - NGINX_PORT=3000
      - PORT=3001
      - PUID=0
      - PGID=0
      - UMASK=000
      - TZ=Asia/Shanghai
      - SUPERUSER=admin
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接

  jellyfin: # 服务名称
    image: nyanmisaka/jellyfin:latest # 镜像名称（可更改冒号后版本）
    container_name: jellyfin # 容器名称（可更改）
    privileged: true # 配置最高权限
    devices:
     - /dev/dri:/dev/dri
    ports: # 容器端口（可更改冒号前端口）
      - 3010:8096
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /vol1/1000/Docker/jellyfin/config:/config
      - /vol1/1000/Docker/jellyfin/cache:/cache
      - /vol1/1000/Video:/video
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接

  qbittorrent: # 服务名称
    image: linuxserver/qbittorrent:4.6.6 # 镜像名称（可更改冒号后版本）
    container_name: qbittorrent # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 3020:3020
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /vol1/1000/Docker/qbittorrent:/config
      - /vol1/1000/Video:/downloads
    environment: # 环境变量
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - WEBUI_PORT=3020
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接

  transmission: # 服务名称
    image: linuxserver/transmission:4.0.5 # 镜像名称（可更改冒号后版本）
    container_name: transmission # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 3030:9091
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /vol1/1000/Docker/transmission:/config
      - /vol1/1000/Video:/downloads
    environment: # 环境变量
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - TRANSMISSION_WEB_HOME=/config/webui/Transmission Theme
      - USER=root
      - PASS=root
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接

  iyuuplus: # 服务名称
    image: iyuucn/iyuuplus:latest # 镜像名称（可更改冒号后版本）
    container_name: iyuuplus # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 3040:8780
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /vol1/1000/Docker/iyuuplus/iyuu:/iyuu
      - /vol1/1000/Docker/iyuuplus/data:/data
      - /vol1/1000/Docker/qbittorrent/qBittorrent/BT_backup:/qb
      - /vol1/1000/Docker/transmission/torrents:/tr
    environment: # 环境变量
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接

  xunlei: # 服务名称
    image: cnk3x/xunlei:latest # 镜像名称（可更改冒号后版本）
    container_name: xunlei # 容器名称（可更改）
    privileged: true # 配置最高权限
    ports: # 容器端口（可更改冒号前端口）
      - 3050:2345
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /vol1/1000/Docker/xunlei:/xunlei/data
      - /vlo1/1000/Downloads:/xunlei/downloads
    environment: # 环境变量
      - XL_GID=0
      - XL_UID=0
      - TZ=Asia/Shanghai
      - XL_DASHBOARD_USERNAME=admin
      - XL_DASHBOARD_PASSWORD=admin
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接  
  
  jackett: # 服务名称
    image: linuxserver/jackett:latest # 镜像名称（可更改冒号后版本）
    container_name: jackett # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 3060:9117
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /vol1/1000/Docker/jackett/config:/config
      - /vol1/1000/Docker/jackett/downloads:/downloads
    environment: # 环境变量
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - AUTO_UPDATE=false
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接

  alist-tvbox:
    image: haroldli/xiaoya-tvbox:latest
    container_name: alist-tvbox
    ports:
      - 3070:4567
      - 3080:80
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /vol1/1000/Docker/xiaoya:/data
    environment: # 环境变量
      - ALIST_PORT=3080
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接

  aipan:
    image: fooololo/aipan-netdisk-search:latest
    container_name: aipan
    ports:
      - 3090:3000
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接

  vertex:
    image: lswl/vertex:latest
    container_name: vertex
    ports: # 容器端口（可更改冒号前端口）
      - 3095:32110
    volumes:
      - /vol1/1000/Docker/vertex:/vertex
    environment:
      - PORT=32110
      - TZ=Asia/Shanghai
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接

#######################  音乐类  ############################

  navidrome: # 服务名称
    image: deluan/navidrome:latest # 镜像名称（可更改冒号后版本）
    container_name: navidrome # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - "4000:4533"
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /vol1/1000/Docker/navidrome:/data
      - /vol1/1000/Music:/music
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接

  music-tag: # 服务名称
    image: xhongc/music_tag_web:latest # 镜像名称（可更改冒号后版本）
    container_name: music-tag-web # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - "4010:8001"
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /vol1/1000/Music:/app/media
      - /vol1/1000/Docker/music-tag-web:/app/data
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接

#######################  小说类  ############################

  reader: # 服务名称
    image: hectorqin/reader:latest # 镜像名称（可更改冒号后版本）
    container_name: reader # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 5000:8080
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /vol1/1000/Docker/reader/log:/log
      - /vol1/1000/Docker/reader/storage:/storage
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接

#######################  漫画类  ############################ 

  komga: # 服务名称
    image: gotson/komga:latest # 镜像名称（可更改冒号后版本）
    container_name: komga # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 6010:25600
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /vol1/1000/Docker/komga/config:/config
      - /vol1/1000/Docker/komga/data:/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    network_mode: bridge # 总是启动容器
    restart: always # 网络桥接

#######################  办公类  ############################ 

  #wps-office: # 服务名称
  #  image: linuxserver/wps-office:chinese # 镜像名称（可更改冒号后版本）
  #  container_name: wps-office # 容器名称（可更改）
  #  ports: # 容器端口（可更改冒号前端口）
  #    - 7000:3000
  #    - 7001:3001
  #  volumes: # 冒号前替换成自身路径即可（可更改）
  #    - /vol1/1000/Docker/wps-office/config:/config
  #    - /vol1/1000/Docker/wps-office/Desktop:/config/Desktop
  #    - /vol1/1000/Docker/wps-office/Fonts:/usr/share/fonts/wps-fonts
  #  environment: # 环境变量
  #    - PUID=0
  #    - PGID=0
  #    - TZ=Asia/Shanghai
  #    - CUSTOM_USER=admin
  #    - PASSWORD=admin
  #  restart: always # 总是启动容器
  #  network_mode: bridge # 网络桥接

  verysync: # 服务名称
    image: jonnyan404/verysync:latest # 镜像名称（可更改冒号后版本）
    container_name: verysync # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 7010:8886
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /vol1/1000/synchronous:/data
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接
    
  stirling-pdf: # 服务名称
    image: frooodle/s-pdf:latest # 镜像名称（可更改冒号后版本）
    container_name: pdftool # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 7020:8080
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /vol1/1000/Docker/pdftool/tessdata:/usr/share/tessdata
      - /vol1/1000/Docker/pdftool/configs:/configs
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_GB
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接

  kkfileview: # 服务名称
    image: pi4k8s/kkfileview:4.4.0 # 镜像名称（可更改冒号后版本）
    container_name: kkfileview # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
    - 7030:8012
    volumes: # 冒号前替换成自身路径即可（可更改）
       - /vol1/1000/Docker/kkfileview:/opt/kkFileView-4.4.0
    environment: 
      - KK_OFFICE_PREVIEW_TYPE=pdf
      - KK_OFFICE_PREVIEW_SWITCH_DISABLED=true
      - KK_PDF_DOWNLOAD_DISABLE=true
      - KK_FILE_UPLOAD_ENABLED=false
      - KK_CONTEXT_PATH=/
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接

  siyuan-note-unlock: # 服务名称
    image: apkdv/siyuan-unlock:latest # 镜像名称（可更改冒号后版本）
    container_name: siyuan-note-unlock # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 7040:6806/tcp
    command:
      - --workspace=/siyuan/workspace/
      - --accessAuthCode=100
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /vol1/1000/Docker/siyuan-note-unlock:/siyuan/workspace
    environment:
      - PUID=1000
      - PGID=100
      - UMASK=022
      - TZ=Asia/Shanghai
      - LANG=zh_CN.UTF-8
      - LC_ALL=zh_CN.UTF-8
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接

  alist: # 服务名称
    image: xhofe/alist:latest # 镜像名称（可更改冒号后版本）
    container_name: alist # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 7050:5244
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /vol1/1000/Docker/alist:/opt/alist/data
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=Asia/Shanghai
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接

#######################  网络类  ############################ 

  frpc: # 服务名称
    image: snowdreamtech/frpc # 镜像名称（可更改冒号后版本）
    container_name: frpc # 容器名称（可更改）
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /vol1/1000/Frpc:/etc/frp
    command: -c /etc/frp/frpc.ini # 启动命令
    restart: always # 总是启动容器
    network_mode: host # 网络本地

  #v2raya: # 服务名称
  #  image: v2raya/v2raya:latest # 镜像名称（可更改冒号后版本）
  #  container_name: v2raya # 容器名称（可更改）
  #  privileged: true
  #  ports: # 容器端口（可更改冒号前端口）
  #    - 8010:2017
  #  volumes: # 冒号前替换成自身路径即可（可更改）
  #    - /vol1/1000/Docker/v2raya:/etc/v2raya
  #  environment: # 环境变量
  #    - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  #  restart: always # 总是启动容器
  #  network_mode: bridge # 网络桥接

#######################  美化类  ############################ 

  sun-panel: # 服务名称
    image: hslr/sun-panel:latest # 镜像名称（可更改冒号后版本）
    container_name: sun-panel # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 9000:3002
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /vol1/1000/Docker/sun-panel:/app/conf
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接

#######################  娱乐类  ############################

  emulatorjs: # 服务名称
    image: lscr.io/linuxserver/emulatorjs:latest # 镜像名称（可更改冒号后版本）
    container_name: emulatorjs # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 10001:3000
      - 10000:80
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /vol1/1000/Docker/emulatorjs/config:/config
      - /vol1/1000/Docker/emulatorjs/data:/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接

#######################  系统类  ############################

  qinglong: # 服务名称
    image: whyour/qinglong:latest # 镜像名称（可更改冒号后版本）
    container_name: qinglong # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 11000:5700
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /vol1/1000/Docker/qinglong:/ql/data
    environment:
      - QlPort=5700
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接
    
  homeassistant: # 服务名称
    image: homeassistant/home-assistant:latest # 镜像名称（可更改冒号后版本）
    container_name: homeassistant # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 11010:8123
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /vol1/1000/Docker/homeassistant:/config
    environment:
      - TZ=Asia/Shanghai
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接
