services:

  1panel: # 服务名称
    image: koryking/1panel:latest # 镜像名称（可更改冒号后版本）
    container_name: 1panel # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 11000:10086
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/dm-1/.ugreen_nas/509155/Docker/1panel:/opt/1panel
      - /mnt/dm-1/.ugreen_nas/509155/:/mnt/dm-1/.ugreen_nas/509155/
    environment:
      - TZ=Asia/Shanghai
      - PANEL_BASE_DIR=/opt/1panel
      - PANEL_PORT=10086
      - PANEL_ENTRANCE=123456
      - PANEL_USERNAME=admin
      - PANEL_PASSWORD=password
    network_mode: bridge # 总是启动容器
    restart: always # 网络桥接

  qinglong: # 服务名称
    image: whyour/qinglong:latest # 镜像名称（可更改冒号后版本）
    container_name: qinglong # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 11010:5700
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /mnt/dm-1/.ugreen_nas/509155/Docker/qinglong:/ql/data
    environment:
      - QlPort=5700
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接
    
  homeassistant: # 服务名称
    image: homeassistant/home-assistant:latest # 镜像名称（可更改冒号后版本）
    container_name: homeassistant # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 11020:8123
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /mnt/dm-1/.ugreen_nas/509155/Docker/homeassistant:/config
    environment:
      - TZ=Asia/Shanghai
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接
 
  mysql:
    image: mariadb:latest
    container_name: mysql # 容器名称（可更改）
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /mnt/dm-1/.ugreen_nas/509155/Docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD: password
      - MYSQL_DATABASE: teamspeak
    restart: always # 总是启动容器
