services:

  wps-office: # 服务名称
    image: linuxserver/wps-office:chinese # 镜像名称（可更改冒号后版本）
    container_name: wps-office # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 7000:3000
      - 7001:3001
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /mnt/dm-1/.ugreen_nas/509155/Docker/wps-office/config:/config
      - /mnt/dm-1/.ugreen_nas/509155/Docker/wps-office/Desktop:/config/Desktop
      - /mnt/dm-1/.ugreen_nas/509155/Docker/wps-office/Fonts:/usr/share/fonts/wps-fonts
    environment: # 环境变量
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - CUSTOM_USER=admin
      - PASSWORD=admin
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接

  verysync: # 服务名称
    image: jonnyan404/verysync:latest # 镜像名称（可更改冒号后版本）
    container_name: verysync # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 7010:8886
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /mnt/dm-1/.ugreen_nas/509155/Synchronous:/data
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接
    
  stirling-pdf: # 服务名称
    image: frooodle/s-pdf:latest # 镜像名称（可更改冒号后版本）
    container_name: pdftool # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 7020:8080
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /mnt/dm-1/.ugreen_nas/509155/Photo:/usr/share/tessdata
      - /mnt/dm-1/.ugreen_nas/509155/Docker/pdftool/configs:/configs
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_GB
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接

  kkfileview: # 服务名称
    image: pi4k8s/kkfileview:4.4.0 # 镜像名称（可更改冒号后版本）
    container_name: kkfileview # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
    - 7030:8012
    volumes: # 冒号前替换成自身路径即可（可更改）
       - /mnt/dm-1/.ugreen_nas/509155/Docker/kkfileview:/opt/kkFileView-4.4.0
    environment: 
      - KK_OFFICE_PREVIEW_TYPE=pdf
      - KK_OFFICE_PREVIEW_SWITCH_DISABLED=true
      - KK_PDF_DOWNLOAD_DISABLE=true
      - KK_FILE_UPLOAD_ENABLED=false
      - KK_CONTEXT_PATH=/
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接

  siyuan-note-unlock: # 服务名称
    image: apkdv/siyuan-unlock:latest # 镜像名称（可更改冒号后版本）
    container_name: siyuan-note-unlock # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 7040:6806/tcp
    command:
      - --workspace=/siyuan/workspace/
      - --accessAuthCode=100
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /mnt/dm-1/.ugreen_nas/509155/Docker/siyuan-note-unlock:/siyuan/workspace
    environment:
      - PUID=1001
      - PGID=100
      - UMASK=022
      - TZ=Asia/Shanghai
      - LANG=zh_CN.UTF-8
      - LC_ALL=zh_CN.UTF-8
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接
    
  alist: # 服务名称
    image: xhofe/alist:latest # 镜像名称（可更改冒号后版本）
    container_name: alist # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 7050:5244
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /mnt/dm-1/.ugreen_nas/509155/Docker/alist:/opt/alist/data
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=Asia/Shanghai
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接
  
  newsnow: # 服务名称
    image: ghcr.io/ourongxing/newsnow:latest # 镜像名称（可更改冒号后版本）
    container_name: newsnow # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 7060:4444
    environment:
      - G_CLIENT_ID=
      - G_CLIENT_SECRET=
      - JWT_SECRET=
      - INIT_TABLE=true=
      - ENABLE_CACHE=true
    network_mode: bridge # 总是启动容器
    restart: always # 网络桥接
