services:

#######################  影视类  ############################

  #nastools: # 服务名称
  #  image: nastools/nas-tools:latest # 镜像名称（可更改冒号后版本）
  #  container_name: nastools # 容器名称（可更改）
  #  ports: # 容器端口（可更改冒号前端口）
  #    - 3000:3000 
  #  volumes: # 冒号前替换成自身路径即可（可更改）
  #    - /volume1/@home/Testroot/Docker/nastools:/config
  #    - /volume1/@home/Testroot/Video:/downloads
  #  environment: # 环境变量
  #    - PUID=0
  #    - PGID=0
  #    - TZ=Asia/Shanghai
  #    - UMASK=022
  #  restart: always # 总是启动容器
  #  network_mode: bridge # 网络桥接

  moviepilot: # 服务名称
    image: jxxghp/moviepilot-v2:latest # 镜像名称（可更改冒号后版本）
    container_name: moviepilot # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 3000:3000
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /volume1/@home/Testroot/Video:/downloads
      - /volume1/@home/Testroot/Docker/moviepilot:/config
    environment: # 环境变量
      - NGINX_PORT=3000
      - PORT=3001
      - PUID=0
      - PGID=0
      - UMASK=000
      - TZ=Asia/Shanghai
      - SUPERUSER=admin
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接

  #jellyfin: # 服务名称
  #  image: nyanmisaka/jellyfin:latest # 镜像名称（可更改冒号后版本）
  #  container_name: jellyfin # 容器名称（可更改）
  #  privileged: true # 配置最高权限
  #  devices:
  #   - /dev/dri:/dev/dri
  #  ports: # 容器端口（可更改冒号前端口）
  #    - 3010:8096
  #  volumes: # 冒号前替换成自身路径即可（可更改）
  #    - /volume1/@home/Testroot/Docker/jellyfin/config:/config
  #    - /volume1/@home/Testroot/Docker/jellyfin/cache:/cache
  #    - /volume1/@home/Testroot/Video:/video
  #  restart: always # 总是启动容器
  #  network_mode: bridge # 网络桥接

  emby: # 服务名称
    image: amilys/embyserver:latest # 镜像名称（可更改冒号后版本）
    container_name: embyserver # 容器名称（可更改）
    privileged: true # 配置最高权限
    ports: # 容器端口（可更改冒号前端口）
      - 3010:8096
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /volume1/@home/Testroot/Docker/emby/config:/config
      - /volume1/@home/Testroot/Video:/data
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接

  qbittorrent: # 服务名称
    image: linuxserver/qbittorrent:4.6.6 # 镜像名称（可更改冒号后版本）
    container_name: qbittorrent # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 3020:3020
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /volume1/@home/Testroot/Docker/qbittorrent:/config
      - /volume1/@home/Testroot/Video:/downloads
    environment: # 环境变量
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - WEBUI_PORT=3020
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接

  transmission: # 服务名称
    image: linuxserver/transmission:4.0.5 # 镜像名称（可更改冒号后版本）
    container_name: transmission # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 3030:9091
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /volume1/@home/Testroot/Docker/transmission:/config
      - /volume1/@home/Testroot/Video:/downloads
    environment: # 环境变量
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - TRANSMISSION_WEB_HOME=/config/webui/Transmission Theme
      - USER=root
      - PASS=root
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接

  iyuuplus: # 服务名称
    image: iyuucn/iyuuplus:latest # 镜像名称（可更改冒号后版本）
    container_name: iyuuplus # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 3040:8780
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /volume1/@home/Testroot/Docker/iyuuplus/iyuu:/iyuu
      - /volume1/@home/Testroot/Docker/iyuuplus/data:/data
      - /volume1/@home/Testroot/Docker/qbittorrent/qBittorrent/BT_backup:/qb
      - /volume1/@home/Testroot/Docker/transmission/torrents:/tr
    environment: # 环境变量
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接

  xunlei: # 服务名称
    image: cnk3x/xunlei:latest # 镜像名称（可更改冒号后版本）
    container_name: xunlei # 容器名称（可更改）
    privileged: true # 配置最高权限
    ports: # 容器端口（可更改冒号前端口）
      - 3050:2345
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /volume1/@home/Testroot/Docker/xunlei:/xunlei/data
      - /volume1/@home/Testroot/Downloads:/xunlei/downloads
    environment: # 环境变量
      - XL_GID=0
      - XL_UID=0
      - TZ=Asia/Shanghai
      - XL_DASHBOARD_USERNAME=admin
      - XL_DASHBOARD_PASSWORD=admin
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接  
  
  #jackett: # 服务名称
  #  image: linuxserver/jackett:latest # 镜像名称（可更改冒号后版本）
  #  container_name: jackett # 容器名称（可更改）
  #  ports: # 容器端口（可更改冒号前端口）
  #    - 3060:9117
  #  volumes: # 冒号前替换成自身路径即可（可更改）
  #    - /volume1/@home/Testroot/Docker/jackett/config:/config
  #    - /volume1/@home/Testroot/Docker/jackett/downloads:/downloads
  #  environment: # 环境变量
  #    - PUID=0
  #    - PGID=0
  #    - TZ=Asia/Shanghai
  #    - AUTO_UPDATE=false
  #  restart: always # 总是启动容器
  #  network_mode: bridge # 网络桥接

  aipan: # 服务名称
    image: fooololo/aipan-netdisk-search:latest # 镜像名称（可更改冒号后版本）
    container_name: aipan # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 3060:3000
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接

  #vertex:
  #  image: lswl/vertex:latest
  #  container_name: vertex
  #  ports: # 容器端口（可更改冒号前端口）
  #    - 3095:32110
  #  volumes:
  #    - /volume1/@home/Testroot/Docker/vertex:/vertex
  #  environment:
  #    - PORT=32110
  #    - TZ=Asia/Shanghai
  #  restart: always # 总是启动容器
  #  network_mode: bridge # 网络桥接

  iptv-api: # 服务名称
    image: guovern/iptv-api:latest # 镜像名称（可更改冒号后版本）
    container_name: iptv-api # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 3070:8000
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /volume1/@home/Testroot/Docker/iptv-api/config:/iptv-api/config
      - /volume1/@home/Testroot/Docker/iptv-api/output:/iptv-api/output
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接
    
  metatube: # 服务名称
    image: metatube/metatube-server:latest # 镜像名称（可更改冒号后版本）
    container_name: metatube # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 3080:8080
    environment: # 环境变量
      - PORT=8080
      - DB_MAX_IDLE_CONNS=0
      - DB_MAX_OPEN_CONNS=0
      - DB_PREPARED_STMT=0
      - DB_AUTO_MIGRATE=0
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接

#######################  音乐类  ############################

  navidrome: # 服务名称
    image: deluan/navidrome:latest # 镜像名称（可更改冒号后版本）
    container_name: navidrome # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - "4000:4533"
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /volume1/@home/Testroot/Docker/navidrome:/data
      - /volume1/@home/Testroot/Music:/music
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接

  music-tag: # 服务名称
    image: xhongc/music_tag_web:latest # 镜像名称（可更改冒号后版本）
    container_name: music-tag-web # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - "4010:8001"
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /volume1/@home/Testroot/Music:/app/media
      - /volume1/@home/Testroot/Docker/music-tag-web:/app/data
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接

#######################  小说类  ############################

  reader: # 服务名称
    image: hectorqin/reader:latest # 镜像名称（可更改冒号后版本）
    container_name: reader # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 5000:8080
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /volume1/@home/Testroot/Docker/reader/log:/log
      - /volume1/@home/Testroot/Docker/reader/storage:/storage
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接

#######################  漫画类  ############################ 

  komga: # 服务名称
    image: gotson/komga:latest # 镜像名称（可更改冒号后版本）
    container_name: komga # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 6010:25600
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /volume1/@home/Testroot/Docker/komga/config:/config
      - /volume1/@home/Testroot/Docker/komga/data:/data
    environment: # 环境变量
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    network_mode: bridge # 总是启动容器
    restart: always # 网络桥接

#######################  办公类  ############################ 

  #wps-office: # 服务名称
  #  image: linuxserver/wps-office:chinese # 镜像名称（可更改冒号后版本）
  #  container_name: wps-office # 容器名称（可更改）
  #  ports: # 容器端口（可更改冒号前端口）
  #    - 7000:3000
  #    - 7001:3001
  #  volumes: # 冒号前替换成自身路径即可（可更改）
  #    - /volume1/@home/Testroot/Docker/wps-office/config:/config
  #    - /volume1/@home/Testroot/Docker/wps-office/Desktop:/config/Desktop
  #    - /volume1/@home/Testroot/Docker/wps-office/Fonts:/usr/share/fonts/wps-fonts
  #  environment: # 环境变量
  #    - PUID=0
  #    - PGID=0
  #    - TZ=Asia/Shanghai
  #    - CUSTOM_USER=admin
  #    - PASSWORD=admin
  #  restart: always # 总是启动容器
  #  network_mode: bridge # 网络桥接

  verysync: # 服务名称
    image: jonnyan404/verysync:latest # 镜像名称（可更改冒号后版本）
    container_name: verysync # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 7010:8886
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /volume1/@home/Testroot/Synchronous:/data
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接
    
  stirling-pdf: # 服务名称
    image: frooodle/s-pdf:latest # 镜像名称（可更改冒号后版本）
    container_name: pdftool # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 7020:8080
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /volume1/@home/Testroot/Docker/pdftool/tessdata:/usr/share/tessdata
      - /volume1/@home/Testroot/Docker/pdftool/configs:/configs
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_GB
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接

  kkfileview: # 服务名称
    image: pi4k8s/kkfileview:4.4.0 # 镜像名称（可更改冒号后版本）
    container_name: kkfileview # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
    - 7030:8012
    volumes: # 冒号前替换成自身路径即可（可更改）
       - /volume1/@home/Testroot/Docker/kkfileview:/opt/kkFileView-4.4.0
    environment: 
      - KK_OFFICE_PREVIEW_TYPE=pdf
      - KK_OFFICE_PREVIEW_SWITCH_DISABLED=true
      - KK_PDF_DOWNLOAD_DISABLE=true
      - KK_FILE_UPLOAD_ENABLED=false
      - KK_CONTEXT_PATH=/
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接

  siyuan-note-unlock: # 服务名称
    image: apkdv/siyuan-unlock:latest # 镜像名称（可更改冒号后版本）
    container_name: siyuan-note-unlock # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 7040:6806/tcp
    command:
      - --workspace=/siyuan/workspace/
      - --accessAuthCode=100
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /volume1/@home/Testroot/Docker/siyuan-note-unlock:/siyuan/workspace
    environment:
      - PUID=1000
      - PGID=100
      - UMASK=022
      - TZ=Asia/Shanghai
      - LANG=zh_CN.UTF-8
      - LC_ALL=zh_CN.UTF-8
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接

  alist: # 服务名称
    image: xhofe/alist:latest # 镜像名称（可更改冒号后版本）
    container_name: alist # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 7050:5244
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /volume1/@home/Testroot/Docker/alist:/opt/alist/data
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=Asia/Shanghai
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接
  
  newsnow: # 服务名称
    image: ghcr.io/ourongxing/newsnow:latest # 镜像名称（可更改冒号后版本）
    container_name: newsnow # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 7060:4444
    environment:
      - G_CLIENT_ID=
      - G_CLIENT_SECRET=
      - JWT_SECRET=
      - INIT_TABLE=true=
      - ENABLE_CACHE=true
    network_mode: bridge # 总是启动容器
    restart: always # 网络桥接
    
#######################  网络类  ############################ 

  firefox: # 服务名称
    image: jlesage/firefox:latest # 镜像名称（可更改冒号后版本）
    container_name: firefox # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 8010:5800
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /volume1/@home/Testroot/Docker/firefox/config:/config:rw
      - /volume1/@home/Testroot/Docker/firefox/fonts:/usr/share/fonts
      - /volume1/@home/Testroot/Downloads:/config/downloads
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接

  #npc: # 服务名称
  #  image: yisier1/npc:latest # 镜像名称（可更改冒号后版本）
  #  container_name: npc # 容器名称（可更改）
  #  volumes: # 冒号前替换成自身路径即可（可更改）
  #    - /volume1/@home/Testroot/Docker/npc:/conf
  #  command: -server=47.243.80.27:8024 -vkey=自行填写密钥 -type=tcp # 启动命令
  #  restart: always # 总是启动容器
  #  network_mode: host # 网络本地

  #frpc: # 服务名称
  #  image: snowdreamtech/frpc # 镜像名称（可更改冒号后版本）
  #  container_name: frpc # 容器名称（可更改）
  #  volumes: # 冒号前替换成自身路径即可（可更改）
  #    - /volume1/@home/Testroot/Frpc:/etc/frp
  #  command: -c /etc/frp/frpc.ini # 启动命令
  #  restart: always # 总是启动容器
  #  network_mode: host # 网络本地

  #v2raya: # 服务名称
  #  image: v2raya/v2raya:latest # 镜像名称（可更改冒号后版本）
  #  container_name: v2raya # 容器名称（可更改）
  #  privileged: true
  #  ports: # 容器端口（可更改冒号前端口）
  #    - 8020:2017
  #  volumes: # 冒号前替换成自身路径即可（可更改）
  #    - /volume1/@home/Testroot/Docker/v2raya:/etc/v2raya
  #  environment: # 环境变量
  #    - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  #  restart: always # 总是启动容器
  #  network_mode: bridge # 网络桥接

#######################  美化类  ############################ 

  sun-panel: # 服务名称
    image: hslr/sun-panel:latest # 镜像名称（可更改冒号后版本）
    container_name: sun-panel # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 9000:3002
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /volume1/@home/Testroot/Docker/sun-panel:/app/conf
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接

#######################  娱乐类  ############################

  #emulatorjs: # 服务名称
  #  image: lscr.io/linuxserver/emulatorjs:latest # 镜像名称（可更改冒号后版本）
  #  container_name: emulatorjs # 容器名称（可更改）
  #  ports: # 容器端口（可更改冒号前端口）
  #    - 10001:3000
  #    - 10000:80
  #  volumes: # 冒号前替换成自身路径即可（可更改）
  #    - /volume1/@home/Testroot/Docker/emulatorjs/config:/config
  #    - /volume1/@home/Testroot/Docker/emulatorjs/data:/data
  #  environment:
  #    - PUID=1000
  #    - PGID=1000
  #    - TZ=Asia/Shanghai
  #  restart: always # 总是启动容器
  #  network_mode: bridge # 网络桥接
  
  #teamspeak: # 服务名称
  #  image: teamspeak:latest # 镜像名称（可更改冒号后版本）
  #  container_name: teamspeak # 容器名称（可更改）
  #  ports: # 容器端口（可更改冒号前端口）
  #    - 10010:9987/udp
  #    - 10011:30033
  #    - 10012:41144
  #    - 10013:10011
  #  volumes: # 冒号前替换成自身路径即可（可更改）
  #    - /volume1/@home/Testroot/Docker/teamspeak:/var/ts3server
  #  environment:
  #    TS3SERVER_DB_PLUGIN: ts3db_mariadb
  #    TS3SERVER_DB_SQLCREATEPATH: create_mariadb
  #    TS3SERVER_DB_HOST: db
  #    TS3SERVER_DB_USER: root
  #    TS3SERVER_DB_PASSWORD: password
  #    TS3SERVER_DB_NAME: teamspeak
  #    TS3SERVER_DB_WAITUNTILREADY: 30
  #    TS3SERVER_LICENSE: accept
  #  restart: always # 总是启动容器
  #  network_mode: bridge # 网络桥接

#######################  系统类  ############################

  1panel: # 服务名称
    image: koryking/1panel:latest # 镜像名称（可更改冒号后版本）
    container_name: 1panel # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 11000:10086
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/@home/Testroot/Docker/1panel:/opt/1panel
      - /volume1/@home/Testroot/:/volume1/@home/Testroot/
    environment:
      - TZ=Asia/Shanghai
      - PANEL_BASE_DIR=/opt/1panel
      - PANEL_PORT=10086
      - PANEL_ENTRANCE=123456
      - PANEL_USERNAME=admin
      - PANEL_PASSWORD=password
    network_mode: bridge # 总是启动容器
    restart: always # 网络桥接

  qinglong: # 服务名称
    image: whyour/qinglong:latest # 镜像名称（可更改冒号后版本）
    container_name: qinglong # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 11010:5700
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /volume1/@home/Testroot/Docker/qinglong:/ql/data
    environment:
      - QlPort=5700
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接
    
  #homeassistant: # 服务名称
  #  image: homeassistant/home-assistant:latest # 镜像名称（可更改冒号后版本）
  #  container_name: homeassistant # 容器名称（可更改）
  #  ports: # 容器端口（可更改冒号前端口）
  #    - 11020:8123
  #  volumes: # 冒号前替换成自身路径即可（可更改）
  #    - /volume1/@home/Testroot/Docker/homeassistant:/config
  #  environment:
  #    - TZ=Asia/Shanghai
  #  restart: always # 总是启动容器
  #  network_mode: bridge # 网络桥接
 
  #mysql:
  #  image: mariadb:latest
  #  container_name: mysql # 容器名称（可更改）
  #  volumes: # 冒号前替换成自身路径即可（可更改）
  #    - /volume1/@home/Testroot/Docker/mysql:/var/lib/mysql
  #  environment:
  #    MYSQL_ROOT_PASSWORD: password
  #    MYSQL_DATABASE: teamspeak
  #  restart: always # 总是启动容器
